import React, { Component } from 'react';
import ProjList from './ProjList';
import Py from '../Images/py.png';
import BC from '../Images/bc.png';
import Qt from '../Images/qt.png';
import Cov from '../Images/coverity.png';
import RDS from '../Images/rds.png';
import Java from '../Images/java.png';
import SQL from '../Images/sql.png';
import RLogo from '../Images/react.png';

export class Projects extends Component {
  render() {
    const projects = [
      {
        title: "3CT: Coverity Code Correction Tool",
        desc: "A tool that generates potential solutions for defective files by \
        processing artifacts generated by Coverity Analysis. For each file, \
        users are able to view what kind of defect was detected, as well as \
        the proposed solution, with the ability to apply the solution to the file.",
        date: "June 2019 - August 2019",
        class: "proj proj-1",
        techImg: [Py, Cov, Qt, BC],
        techTxt: ["Python", "Coverity Analysis", "PyQt", "BeyondCompare"]
      },
      {
        title: "ReciPull",
        desc: "A web application that takes a user-inputted list of ingredients (through \
          the app or Alexa skill) and outputs recipes containing those ingredients. \
          Users are able to filter searches, as well as upvote or downvote recipes.",
        date: "April 2019 - June 2019",
        class: "proj proj-2",
        techImg: [Java, SQL, RLogo, RDS],
        techTxt: ["Java", "MySQL", "ReactJS", "AWS Relational Database Service"]
      },
    ]
    return(
      <div id="projects">
        <div className="proj-header">My Projects</div>
        <div className="proj-wrapper">
          <ProjList projects={projects} />
        </div>
      </div>
    );
  }
}
export default Projects;